include: 'https://raw.githubusercontent.com/Checkmarx/ci-cd-integrations/main/GitlabCICD/v1/CheckmarxCLI.gitlab-ci.yml'

#You can check the options that better fit your use case in the documentation page, https://checkmarx.atlassian.net/wiki/spaces/AST/pages/3080194906/scan+create#Flags
variables:  
  CX_PROJECT_NAME: "$CI_PROJECT_PATH"

stages:
  - build
  - test

build_application:
    stage: build
    script:
      - echo "Building application..."
      - echo "Finishing Building application"

E2ETest_application:
    stage: test
    script:
      - echo "Testing application..."
      - echo "Testing Building application"

